development:
  utxo_endpoint_url: http://localhost:8081
  block_syncer_url: http://localhost:8332
test:
  utxo_endpoint_url:
  block_syncer_url:
production:
  utxo_endpoint_url: http://ec2-35-162-156-151.us-west-2.compute.amazonaws.com:8081
  block_syncer_url: http://localhost:8332
   
